/**
 * Build-time access to moment content. Runs only in Server Components during
 * `next build` / `next dev`, never in the browser.
 *
 * - The moment wall comes from content/moments/candidates.md, the master list.
 * - A moment is "built" once content/moments/{id}.json exists.
 * - A built moment's full state comes from public/data/moments/{id}.json,
 *   generated by the pipeline (`cd pipeline && uv run python -m build`).
 */

import fs from "node:fs";
import path from "node:path";

import type { Moment, MomentCandidate, MomentType } from "./types";

const CONTENT_DIR = path.join(process.cwd(), "content", "moments");
const DATA_DIR = path.join(process.cwd(), "public", "data", "moments");

const DECADE_HEADING = /^## (.+)$/;
const TABLE_ROW = /^\| (\d+) \| (.+?) \| (.+?) \| (.+?) \| (.+?) \|$/;

/** Every moment in candidates.md, in order, linked to its content file if it's built. */
export function getMomentCandidates(): MomentCandidate[] {
  const builtByNumber = new Map(getBuiltMoments().map((m) => [m.number, m]));
  const candidates: MomentCandidate[] = [];
  let era = "";

  for (const line of fs.readFileSync(path.join(CONTENT_DIR, "candidates.md"), "utf8").split("\n")) {
    const heading = line.match(DECADE_HEADING);
    if (heading) era = heading[1];
    const row = line.match(TABLE_ROW);
    if (!row) continue;

    const [, number, game, description, state, type] = row;
    const built = builtByNumber.get(Number(number));
    candidates.push({
      number: Number(number),
      era,
      year: Number(game.slice(0, 4)),
      game,
      description,
      state,
      type: type as MomentType,
      id: built?.id ?? null,
      title: built?.title ?? null,
      hook: built?.hook ?? null,
    });
  }
  return candidates;
}

type MomentContent = { id: string; number: number; title: string; hook: string };

/** Hand-written moment files in content/moments/. */
function getBuiltMoments(): MomentContent[] {
  return fs
    .readdirSync(CONTENT_DIR)
    .filter((file) => file.endsWith(".json"))
    .map((file) => JSON.parse(fs.readFileSync(path.join(CONTENT_DIR, file), "utf8")) as MomentContent);
}

export function getBuiltMomentIds(): string[] {
  return getBuiltMoments().map((m) => m.id);
}

/** A built moment's full state, as exported by the pipeline. */
export function getMoment(id: string): Moment {
  const file = path.join(DATA_DIR, `${id}.json`);
  if (!fs.existsSync(file)) {
    throw new Error(`${path.relative(process.cwd(), file)} is missing. Build the data first: cd pipeline && uv run python -m build`);
  }
  return JSON.parse(fs.readFileSync(file, "utf8")) as Moment;
}
